[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
qvs_emission_engine = "6pw4r97FHFyTsqC5Z7NHYA278i4HgWjK16wmrxWgTXe2"

[provider]
cluster = "localnet"
wallet = "C:/Users/kasik/.config/solana/id.json"

[scripts]
test = "anchor test"

[hooks]
